project_id = "shnvkktsukzauoacaqfi"

[functions.sheets-ringkasan]
verify_jwt = false

[functions.sheets-konsep]
verify_jwt = false

[functions.sheets-indikator]
verify_jwt = false

[functions.tanya-santika]
verify_jwt = false
